"""Request DTO Abstraction Module.

This module defines the I request DTO interface that all request
DTOs should inherit from. It enforces common fields and validation
rules for all incoming requests.

Usage:
    >>> from dtos.requests.abstraction import IRequestDTO
    >>>
    >>> class MyRequestDTO(IRequestDTO):
    ...     custom_field: str
"""

import uuid

from pydantic import field_validator

from abstractions.dto import IDTO


class IRequestDTO(IDTO):
    """Abstract base for all request DTOs.

    Inherits :class:`abstractions.dto.IDTO`.

    This dto class defines common fields and validation rules that
    all request DTOs must include. Currently, it requires a reference
    number for request tracking.

    Attributes:
        reference_urn (str): A valid UUID string for request identification.
            Used for client-side request tracking and correlation.

    Validation:
        - reference_urn must not be empty
        - reference_urn must be a valid UUID format

    Example:
        >>> from dtos.requests.abstraction import IRequestDTO
        >>>
        >>> class OrderRequestDTO(IRequestDTO):
        ...     product_id: str
        ...     quantity: int
        ...
        >>> # Valid request
        >>> request = OrderRequestDTO(
        ...     reference_urn="550e8400-e29b-41d4-a716-446655440000",
        ...     product_id="prod-123",
        ...     quantity=2
        ... )
        >>>
        >>> # Invalid - not a UUID
        >>> request = OrderRequestDTO(
        ...     reference_urn="not-a-uuid",  # Raises ValueError
        ...     product_id="prod-123",
        ...     quantity=2
        ... )

    Note:
        The reference_urn is typically generated by the client and
        passed in the request body. It's different from the server-side
        URN (Unique Request Number) which is generated by middleware.

    """

    reference_urn: str
    """Client-provided UUID for request identification and tracking."""

    @field_validator("reference_urn")
    @classmethod
    def validate_reference_urn(cls, v: str) -> str:
        """Validate that reference_urn is a non-empty valid UUID.

        Args:
            v (str): The reference number to validate.

        Returns:
            str: The validated reference number.

        Raises:
            ValueError: If the reference number is empty or not a valid UUID.

        """
        if not v or not v.strip():
            raise ValueError("Reference number cannot be empty.")
        try:
            uuid.UUID(v)
        except Exception:
            raise ValueError("Reference number must be a valid UUID.")
        return v
